import type { Station, StationsResponse } from './types'

// 開發階段用假資料:backend /api/stations 就緒前,讓地圖相關 UI 可以先行開發與檢視
export const mockStations: Station[] = [
  {
    sno: '500101001',
    sna: '板橋區公所',
    snaen: 'Banqiao Dist. Office',
    sarea: '板橋區',
    sareaen: 'Banqiao Dist.',
    ar: '新北市板橋區中山路一段161號',
    aren: 'No.161, Sec. 1, Zhongshan Rd., Banqiao Dist.',
    lat: 25.0117,
    lng: 121.4627,
    totalQuantity: 20,
    availableRent: 4,
    availableReturn: 16,
    yb2Quantity: 3,
    eybQuantity: 1,
    active: true,
    updateTime: new Date().toISOString(),
  },
  {
    sno: '500102002',
    sna: '新埔捷運站',
    snaen: 'Xinpu MRT Station',
    sarea: '板橋區',
    sareaen: 'Banqiao Dist.',
    ar: '新北市板橋區文化路一段268號',
    aren: 'No.268, Sec. 1, Wenhua Rd., Banqiao Dist.',
    lat: 25.0158,
    lng: 121.4646,
    totalQuantity: 32,
    availableRent: 12,
    availableReturn: 20,
    yb2Quantity: 8,
    eybQuantity: 0,
    active: true,
    updateTime: new Date().toISOString(),
  },
  {
    sno: '500201001',
    sna: '淡水漁人碼頭',
    snaen: 'Fisherman’s Wharf',
    sarea: '淡水區',
    sareaen: 'Tamsui Dist.',
    ar: '新北市淡水區觀海路199號',
    aren: 'No.199, Guanhai Rd., Tamsui Dist.',
    lat: 25.1801,
    lng: 121.3999,
    totalQuantity: 24,
    availableRent: 0,
    availableReturn: 24,
    yb2Quantity: 5,
    eybQuantity: 2,
    active: true,
    updateTime: new Date().toISOString(),
  },
  {
    sno: '500301001',
    sna: '八里左岸',
    snaen: 'Bali Left Bank',
    sarea: '八里區',
    sareaen: 'Bali Dist.',
    ar: '新北市八里區觀海大道9號',
    aren: 'No.9, Guanhai Blvd., Bali Dist.',
    lat: 25.1467,
    lng: 121.3999,
    totalQuantity: 18,
    availableRent: 9,
    availableReturn: 9,
    yb2Quantity: 2,
    eybQuantity: 0,
    active: true,
    updateTime: new Date().toISOString(),
  },
  {
    sno: '500401001',
    sna: '三重國民運動中心',
    snaen: 'Sanchong Sports Center',
    sarea: '三重區',
    sareaen: 'Sanchong Dist.',
    ar: '新北市三重區三和路四段155號',
    aren: 'No.155, Sec. 4, Sanhe Rd., Sanchong Dist.',
    lat: 25.0614,
    lng: 121.4869,
    totalQuantity: 26,
    availableRent: 20,
    availableReturn: 6,
    yb2Quantity: 4,
    eybQuantity: 1,
    active: false,
    updateTime: new Date().toISOString(),
  },
]

export function buildMockStationsResponse(): StationsResponse {
  return {
    updatedAt: new Date().toISOString(),
    cached: false,
    stale: false,
    cacheAgeSeconds: 0,
    total: mockStations.length,
    data: mockStations,
  }
}

export const mockAreas = ['板橋區', '淡水區', '八里區', '三重區']
